{extends file="base.tpl"}

{block name="title"}{$article.name} - My Blog{/block}

{block name="content"}

    {*  HTML layout generated by Claude code  *}
    <article class="article-full">
        <h2>{$article.name}</h2>
        <p class="meta">
            in
            {foreach from=$article.categories item=cat name=catLoop}
                <a href="index.php?page=category&amp;id={$cat.id}">{$cat.name}</a>{if !$smarty.foreach.catLoop.last}, {/if}
            {foreachelse}
                Uncategorized
            {/foreach}
            &middot; {$article.created_at} &middot; {$article.views} views
        </p>
        {if $article.image}
            <img src="{$article.image}" alt="{$article.name}">
        {/if}
        {if $article.description}
            <p><em>{$article.description}</em></p>
        {/if}
        <div class="article-text">
            {$article.content nofilter}
        </div>
    </article>
    {*  End Claude code  *}

    {if $relatedArticles}
        <section class="related-articles">
            <h3>Related Articles</h3>
            <ul class="article-list">
                {foreach from=$relatedArticles item=related}
                    <li class="article-item">
                        {if $related.image}
                            <img src="{$related.image}" alt="{$related.name}">
                        {/if}
                        <div>
                            <h3><a href="index.php?page=article&amp;id={$related.id}">{$related.name}</a></h3>
                            <p>{$related.description}</p>
                            <p class="meta">{$related.created_at} &middot; {$related.views} views</p>
                        </div>
                    </li>
                {/foreach}
            </ul>
        </section>
    {/if}

    <p><a href="index.php">&laquo; Back to Home</a></p>
{/block}
