<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{block name="title"}Blog{/block}</title>
    {* Generated by Claude code *}
    <style>
        :root {
            --cream: #F5F7D4;
            --yellow-green: #E4F132;
            --light-green: #98CA32;
            --mid-green: #559E54;
            --dark-green: #0A3409;
        }

        * { box-sizing: border-box; }

        body {
            font-family: Arial, sans-serif;
            max-width: 900px;
            margin: 0 auto;
            padding: 0 20px 20px;
            background: #ffffff;
            color: var(--dark-green);
            line-height: 1.5;
        }

        a { color: var(--mid-green); }
        a:hover { color: var(--dark-green); }

        header {
            background: var(--dark-green);
            margin: 0 -20px 20px;
            padding: 16px 20px;
        }
        header a { text-decoration: none; color: var(--cream); }
        header h1 { margin: 0 0 10px; color: var(--yellow-green); }
        nav a {
            display: inline-block;
            margin-right: 6px;
            padding: 4px 10px;
            border-radius: 4px;
            color: var(--cream);
        }
        nav a:hover { background: var(--mid-green); color: #ffffff; }

        .category-section { margin-bottom: 30px; }
        .category-section h2 {
            color: var(--dark-green);
            border-left: 4px solid var(--light-green);
            padding-left: 10px;
        }

        .article-list { list-style: none; padding: 0; margin: 0; }
        .article-item {
            display: flex;
            gap: 15px;
            padding: 15px 0;
            border-bottom: 1px solid var(--cream);
        }
        .article-item img { width: 120px; height: 90px; object-fit: cover; border-radius: 6px; }
        .article-item h3 { margin: 0 0 5px 0; }
        .article-item h3 a { text-decoration: none; color: var(--dark-green); }
        .article-item h3 a:hover { color: var(--mid-green); }
        .meta { color: var(--mid-green); font-size: 0.85em; }

        .btn-all {
            display: inline-block;
            background: var(--light-green);
            color: var(--dark-green);
            padding: 8px 16px;
            border-radius: 6px;
            text-decoration: none;
            font-weight: bold;
        }
        .btn-all:hover { background: var(--mid-green); color: #ffffff; }

        .sort-form {
            display: flex;
            flex-wrap: wrap;
            align-items: center;
            gap: 12px;
            background: var(--cream);
            padding: 12px 16px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .sort-form select {
            padding: 6px 10px;
            border: 1px solid var(--light-green);
            border-radius: 4px;
            background: #ffffff;
            color: var(--dark-green);
        }
        .sort-form button {
            padding: 7px 16px;
            border: none;
            border-radius: 4px;
            background: var(--mid-green);
            color: #ffffff;
            cursor: pointer;
            font-weight: bold;
        }
        .sort-form button:hover { background: var(--dark-green); }

        .pagination { display: flex; flex-wrap: wrap; gap: 8px; margin: 20px 0; }
        .pagination a, .pagination span {
            padding: 6px 12px;
            border-radius: 4px;
            text-decoration: none;
        }
        .pagination a { background: var(--cream); color: var(--dark-green); }
        .pagination a:hover { background: var(--light-green); }
        .pagination span.active { background: var(--mid-green); color: #ffffff; font-weight: bold; }

        .article-full h2 { color: var(--dark-green); }
        .article-full img { max-width: 100%; height: auto; border-radius: 8px; }
        .article-text { margin-top: 15px; }

        .related-articles {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid var(--light-green);
        }
        .related-articles h3 { color: var(--dark-green); }

        footer {
            margin: 40px -20px 0;
            padding: 14px 20px;
            background: var(--cream);
            border-top: 3px solid var(--light-green);
            color: var(--dark-green);
            font-size: 0.85em;
        }
    </style>
    {* End Claude code *}
</head>
<body>
<header>
    <a href="index.php"><h1>My Blog</h1></a>
    <nav>
        <a href="index.php">Home</a>
        {foreach from=$nav_categories item=navCat}
            <a href="index.php?page=category&amp;id={$navCat.id}">{$navCat.name}</a>
        {/foreach}
    </nav>
</header>

<main>
    {block name="content"}{/block}
</main>

<footer>
    &copy; {$current_year} My Blog
</footer>
</body>
</html>
