<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{block name="title"}Blog{/block}</title>
    <style>
        /*  Generated by Claude code  */
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #222; }
        header { border-bottom: 2px solid #eee; margin-bottom: 20px; padding-bottom: 10px; }
        header a { text-decoration: none; color: #222; }
        nav a { margin-right: 12px; }
        .article-list { list-style: none; padding: 0; }
        .article-item { display: flex; gap: 15px; padding: 15px 0; border-bottom: 1px solid #eee; }
        .article-item img { width: 120px; height: 90px; object-fit: cover; }
        .article-item h3 { margin: 0 0 5px 0; }
        .article-item h3 a { text-decoration: none; color: #1a4d8f; }
        .meta { color: #888; font-size: 0.85em; }
        .article-full img { max-width: 100%; height: auto; }
        footer { margin-top: 40px; padding-top: 10px; border-top: 1px solid #eee; color: #999; font-size: 0.85em; }
        /*  End Claude code  */
    </style>
</head>
<body>
<header>
    <a href="index.php"><h1>My Blog</h1></a>
    <nav>
        <a href="index.php">Home</a>
        {foreach from=$nav_categories item=navCat}
            <a href="index.php?page=category&amp;id={$navCat.id}">{$navCat.name}</a>
        {/foreach}
    </nav>
</header>

<main>
    {block name="content"}{/block}
</main>

<footer>
    &copy; {$current_year} My Blog
</footer>
</body>
</html>
