{extends file="base.tpl"}

{block name="title"}{$category.name} - My Blog{/block}

{block name="content"}
    <h2>{$category.name}</h2>
    {if $category.description}
        <p>{$category.description}</p>
    {/if}

    {*  HTML layout generated by Claude code  *}
    <form method="get" class="sort-form">
        <input type="hidden" name="page" value="category">
        <input type="hidden" name="id" value="{$category.id}">
        <label>
            Sort by:
            <select name="sort">
                <option value="date" {if $sort == 'date'}selected{/if}>Publication date</option>
                <option value="views" {if $sort == 'views'}selected{/if}>View count</option>
            </select>
        </label>
        <label>
            Order:
            <select name="order">
                <option value="desc" {if $order == 'desc'}selected{/if}>Descending</option>
                <option value="asc" {if $order == 'asc'}selected{/if}>Ascending</option>
            </select>
        </label>
        <button type="submit">Apply</button>
    </form>
    {*  End Claude code  *}

    <ul class="article-list">
        {foreach from=$articles item=article}
            <li class="article-item">
                {if $article.image}
                    <img src="{$article.image}" alt="{$article.name}">
                {/if}
                <div>
                    <h3><a href="index.php?page=article&amp;id={$article.id}">{$article.name}</a></h3>
                    <p>{$article.description}</p>
                    <p class="meta">{$article.created_at} &middot; {$article.views} views</p>
                </div>
            </li>
        {foreachelse}
            <li>No articles in this category yet.</li>
        {/foreach}
    </ul>

    {if $totalPages > 1}
        <nav class="pagination">
            {foreach from=$pageNumbers item=pageNum}
                {if $pageNum == $currentPage}
                    <span class="active">{$pageNum}</span>
                {else}
                    <a href="index.php?page=category&amp;id={$category.id}&amp;sort={$sort}&amp;order={$order}&amp;p={$pageNum}">{$pageNum}</a>
                {/if}
            {/foreach}
        </nav>
    {/if}

    <p><a href="index.php">&laquo; Back to Home</a></p>
{/block}
