{* Generated by Claude code  *}

{extends file="base.tpl"}

{block name="title"}Not Found - My Blog{/block}

{block name="content"}
    <h2>Not Found</h2>
    <p>{$message}</p>
    <p><a href="index.php">&laquo; Back to Home</a></p>
{/block}
